<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-EKBQQJUS" failures="4" tests="5" name="Projet_RedmineTest" time="39.589" errors="0" timestamp="2023-12-18T12:26:23 HNE">
  <testcase classname="testCases.TC_03_CreationNouveauProjet_Redmine" name="test_NouveauProjet" time="12.799">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at testCases.TC_03_CreationNouveauProjet_Redmine.test_NouveauProjet(TC_03_CreationNouveauProjet_Redmine.java:57)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- test_NouveauProjet -->
  <testcase classname="testCases.TC_01_EnregistrerNouveauCompte" name="test_Enregistrer_NouveauCompte" time="1.493">
    <failure type="java.lang.AssertionError" message="Test failed expected [Votre compte a Ã©tÃ© crÃ©Ã© et attend l&amp;apos;approbation de l&amp;apos;administrateur.] but found [Votre compte a été créé et attend l&amp;apos;approbation de l&amp;apos;administrateur.]">
      <![CDATA[java.lang.AssertionError: Test failed expected [Votre compte a Ã©tÃ© crÃ©Ã© et attend l'approbation de l'administrateur.] but found [Votre compte a été créé et attend l'approbation de l'administrateur.]
at testCases.TC_01_EnregistrerNouveauCompte.test_Enregistrer_NouveauCompte(TC_01_EnregistrerNouveauCompte.java:45)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- test_Enregistrer_NouveauCompte -->
  <testcase classname="testCases.TC_02_ConnexionRedmine" name="ConnexionRedmine_Test" time="0.931"/>
  <testcase classname="testCases.TC_04_Modifier_ProjetRedmine" name="test_Modifier" time="3.111">
    <failure type="java.lang.AssertionError" message="Test failed expected [Mise Ã  jour effectuÃ©e avec succÃ¨s.] but found [Mise à jour effectuée avec succès.]">
      <![CDATA[java.lang.AssertionError: Test failed expected [Mise Ã  jour effectuÃ©e avec succÃ¨s.] but found [Mise à jour effectuée avec succès.]
at testCases.TC_04_Modifier_ProjetRedmine.test_Modifier(TC_04_Modifier_ProjetRedmine.java:55)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- test_Modifier -->
  <testcase classname="testCases.TC_05_Copier_ProjetRedmine" name="test_Modifier" time="4.06">
    <failure type="java.lang.AssertionError" message="Test failed expected [Mise Ã  jour effectuÃ©e avec succÃ¨s.] but found [Mise à jour effectuée avec succès.]">
      <![CDATA[java.lang.AssertionError: Test failed expected [Mise Ã  jour effectuÃ©e avec succÃ¨s.] but found [Mise à jour effectuée avec succès.]
at testCases.TC_05_Copier_ProjetRedmine.test_Modifier(TC_05_Copier_ProjetRedmine.java:61)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- test_Modifier -->
</testsuite> <!-- Projet_RedmineTest -->
